### ISSUE TITLE
Release ComparisonDashboard on the Marketplace

### ISSUE THREAD

**Issue by mattab** [PiwikPRO/plugin-ComparisonDashboard#1]
The goal of this issue is to release this plugin on the Marketplace. 

 * Make repository public
 * Check build is running on travis.org (it currently runs on Magnum travis PRO) and build is green
 * make images display on the README (they are currently 404)
 * Publish on the Marketplace
 * Link to this plugin from the [Segmentation doc](https://piwik.org/wp-admin/post.php?post=15958&action=edit)

**Comment by diosmosis** [comment]
ComparisonDashboard  added to the marketplace; only think left to do is add a link in the doc.

**Comment by mattab** [comment]
Nice work!

 @diosmosis you have access to the website I think, please add the link. btw if you dont have access ask Thomas who can give you access.

**Comment by diosmosis** [comment]
Link added.

**Comment by mattab** [comment]
it's beautiful to see this plugin in the Marketplace free to all users. already 256 downloads in a few days!
