### ISSUE TITLE
Adding metric to widget's chart causes all charts to load same data

### ISSUE THREAD

**Issue by mgonera** [PiwikPRO/plugin-ComparisonDashboard#4]
I have 3 sites chosen in comparison dashboard, 3rd of them is metasite which consists of previous 2:

![comparison_before_adding_metric](https://cloud.githubusercontent.com/assets/11424829/8639233/bb3738b0-28d3-11e5-8b4c-29256c5b0706.png)

then I enable another metric on one of the charts. all charts will reload with new metric, but with all with data for page of which I added metric on (I added metric on the middle chart):

![comparison_after_adding_metric](https://cloud.githubusercontent.com/assets/11424829/8639236/d7684d80-28d3-11e5-93c6-02a73ddbecd3.png)

**Comment by quba** [comment]
It might have been fixed already. Have you tested using 2.9.1 or 2.13.1?

**Comment by mgonera** [comment]
2.13.1

**Comment by mattab** [comment]
Thanks for report, we will investigate (try to reproduce & fix)
